const produtos = [
  {
    id: 1,
    nome: "Banana",
    preco: "2.00",
    secao: "Hortifruti",
    categoria: "fruta",
    img: "./src/img/bananaimg.png",
    promocao: true,
    precoPromocao: "0.99",
    componentes: ["Potássio", "Vitamina B6", "Vitamina C", "Folatos"],
  },
  {
    id: 2,
    nome: "Morango",
    preco: "2.00",
    secao: "Hortifruti",
    categoria: "fruta",
    img: "./src/img/morangoimg.png",
    promocao: false,
    precoPromocao: "0",
    componentes: ["Fibras", "Vitamina C", "Cálcio", "Ferro"],
  },
  {
    id: 3,
    nome: "Maçã",
    preco: "2.00",
    secao: "Hortifruti",
    categoria: "fruta",
    img: "./src/img/macaimg.png",
    promocao: true,
    precoPromocao: "1.59",
    componentes: ["Potássio", "Vitamina A", "Vitamina E", "Vitamina C"],
  },
  {
    id: 4,
    nome: "Pão",
    preco: "4.00",
    secao: "Panificadora",
    categoria: "Pães",
    img: "./src/img/paoimg.png",
    promocao: true,
    precoPromocao: "2.49",
    componentes: ["Cálcio", "Sódio", "Fibra Alimentar", "Proteínas"],
  },
  {
    id: 5,
    nome: "Leite",
    preco: "5.00",
    secao: "Laticinio",
    categoria: "Leite",
    img: "./src/img/leiteimg.png",
    promocao: false,
    precoPromocao: "0.99",
    componentes: ["Carboidratos", "Proteínas", "Gorduras totais"],
  },
];
